version: '3'
services:
  web:
    image: 060746190874.dkr.ecr.eu-west-1.amazonaws.com/aws-fargate-template:ad1f63453f3d2aa8b7ec7cc988f6050e16564988 #amazon/amazon-ecs-sample
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: tutorial
        awslogs-region: eu-west-1
        awslogs-stream-prefix: web